== Principes pour Cosmos

Lexique un peu particulier pour Cosmos en mode tresse. A utiliser, modifier suivant vos goûts.

* Je propose un univers intéressant
* Je réponds aux questions des autres joueurs sur cet univers
- Les autres joueurs vous poseront souvent des questions: qu'est ce qu'on voit ? y a t'il ça ou ça ? Immergez vous mentalement dans votre monde et commencez simple par répondre ce qui est évident.
* Je décris cet univers
- Evitez de monopoliser la parole donc si vous décrivez un personnage ou un lieu, décrivez le par un trait caractéristique. Si les joueurs s'interesse à ce nouvel objet, vous pourrez alors le détailler plus tard. D'ailleurs ca sera peut etre Chaos qui le fera en l'intégrant dans son intrigue.
* Je tends des perches aux autres joueurs en manque d’inspiration
- Rappelez vous, c'est Chaos qui est en charge de faire avancer son intrigue.
* Je peux créer des merveilles: ce sont des révélations sur le monde
qui n’impactent pas l’intrigue directement mais qui permettent
d’ouvrir des portes
* J’interprète les résultats des oppositions sauf si Chaos décide de le faire (au nom de l'intrigue).
* Je gère les dés du destin
- Quand une opposition a lieu, prendre le nombre de dés manquants pour équilibrer l'opposition. Se défausser des paires opposées pour n'avoir qu'une couleur en dé.
* Je peux avantager ou désavantager les héros en fonction des dés rouges (pro obstacle) ou bleus (pro héros) en ma possession.
- Note: rien de m'y oblige mais cela permet de participer et d'équilibrer les oppositions. C'est comme si on était un spectateur qui pouvait agir sur le récit par rapport à ses souhaits ou à ce qui lui parait plus plausible ou plus en phase avec le rythme du récit.
* J’arbitre en cas de litige
* J’interprète les figurants
* Je peux demander à Chaos de sonner la cavalerie ou le faire moi-même
* Je redonne la main
* Je peux trancher certaines questions à la marge (via le destin)